### ISSUE TITLE
active dev?

### ISSUE THREAD

**Issue by spincraft** [madhu1607/PillPal_LP#2]
Hi,
Please let me know if you are planning on actively developing this APP .
THX

**Comment by madhu1607** [comment]
I have initiated it but the app development is currently on hold

**Comment by spincraft** [comment]
Thanks for your reply.
I’m trying to help out a local drug treatment center.
I was hoping to continue developing with this APP.
Is there any source code that would be helpful or anyone still interested in coding it?
Your comments are welcome
Best,
Don
